project_id = "bqqmfajowxzkdcvmrtyd"

[functions.smart-scan]
verify_jwt = false

[functions.unfollow-check]
verify_jwt = false

[functions.trigger-scan]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.create-baseline]
verify_jwt = false
