project_id = "bqqmfajowxzkdcvmrtyd"

[functions.scan-profiles]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.auto-scan]
verify_jwt = false

[functions.trigger-scan]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false
